version: '3.7'

networks:
  internal-network:
    driver: bridge

services:

  api:
    container_name: api
    build:
      context: ./api
      target: development
    volumes:
      - ./api:/home/node/app
      - /home/node/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file: .env
    networks:
      - internal-network
    command: npm run start:dev

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - internal-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - internal-network
